import { Snippet } from './index';

export const decorationSnippets: Snippet[] = [
  // Postfix decorations (xbar → \overline{x})
  {
    trigger: /([a-zA-Z])bar$/,
    replacement: (match: string[]) => `\\overline{${match[1]}}`,
    options: { mode: 'math', triggerKind: 'auto', priority: 75, wordBoundary: false },
    description: 'Overline (postfix: xbar → \\overline{x})',
    category: 'Decorations',
  },
  {
    trigger: /([a-zA-Z])hat$/,
    replacement: (match: string[]) => `\\hat{${match[1]}}`,
    options: { mode: 'math', triggerKind: 'auto', priority: 75, wordBoundary: false },
    description: 'Hat (postfix: xhat → \\hat{x})',
    category: 'Decorations',
  },
  {
    trigger: /([a-zA-Z])til$/,
    replacement: (match: string[]) => `\\tilde{${match[1]}}`,
    options: { mode: 'math', triggerKind: 'auto', priority: 75, wordBoundary: false },
    description: 'Tilde (postfix: xtil → \\tilde{x})',
    category: 'Decorations',
  },
  {
    trigger: /([a-zA-Z])dot$/,
    replacement: (match: string[]) => `\\dot{${match[1]}}`,
    options: { mode: 'math', triggerKind: 'auto', priority: 75, wordBoundary: false },
    description: 'Dot (postfix: xdot → \\dot{x})',
    category: 'Decorations',
  },
  {
    trigger: /([a-zA-Z])ddot$/,
    replacement: (match: string[]) => `\\ddot{${match[1]}}`,
    options: { mode: 'math', triggerKind: 'auto', priority: 80, wordBoundary: false },
    description: 'Double dot (postfix: xddot → \\ddot{x})',
    category: 'Decorations',
  },
  {
    trigger: /([a-zA-Z])vec$/,
    replacement: (match: string[]) => `\\vec{${match[1]}}`,
    options: { mode: 'math', triggerKind: 'auto', priority: 75, wordBoundary: false },
    description: 'Vector (postfix: xvec → \\vec{x})',
    category: 'Decorations',
  },

  // Castel-style vector shortcuts: v,. and v.,
  {
    trigger: /([a-zA-Z]),\.$/,
    replacement: (match: string[]) => `\\vec{${match[1]}}`,
    options: { mode: 'math', triggerKind: 'auto', priority: 80, wordBoundary: false },
    description: 'Vector (Castel: v,. → \\vec{v})',
    category: 'Decorations',
  },
  {
    trigger: /([a-zA-Z])\.,$/,
    replacement: (match: string[]) => `\\vec{${match[1]}}`,
    options: { mode: 'math', triggerKind: 'auto', priority: 80, wordBoundary: false },
    description: 'Vector (Castel: v., → \\vec{v})',
    category: 'Decorations',
  },

  // Prefix decorations (tab-expand)
  {
    trigger: 'bar',
    replacement: '\\overline{$1}',
    options: { mode: 'math', triggerKind: 'tab', priority: 50, wordBoundary: true },
    tabStops: 1,
    description: 'Overline (prefix)',
    category: 'Decorations',
  },
  {
    trigger: 'hat',
    replacement: '\\hat{$1}',
    options: { mode: 'math', triggerKind: 'tab', priority: 50, wordBoundary: true },
    tabStops: 1,
    description: 'Hat (prefix)',
    category: 'Decorations',
  },
  {
    trigger: 'til',
    replacement: '\\tilde{$1}',
    options: { mode: 'math', triggerKind: 'tab', priority: 50, wordBoundary: true },
    tabStops: 1,
    description: 'Tilde (prefix)',
    category: 'Decorations',
  },
  {
    trigger: 'wbar',
    replacement: '\\overline{$1}',
    options: { mode: 'math', triggerKind: 'tab', priority: 50, wordBoundary: true },
    tabStops: 1,
    description: 'Wide overline',
    category: 'Decorations',
  },
  {
    trigger: 'what',
    replacement: '\\widehat{$1}',
    options: { mode: 'math', triggerKind: 'tab', priority: 50, wordBoundary: true },
    tabStops: 1,
    description: 'Wide hat',
    category: 'Decorations',
  },
  {
    trigger: 'wtil',
    replacement: '\\widetilde{$1}',
    options: { mode: 'math', triggerKind: 'tab', priority: 50, wordBoundary: true },
    tabStops: 1,
    description: 'Wide tilde',
    category: 'Decorations',
  },
  {
    trigger: 'und',
    replacement: '\\underline{$1}',
    options: { mode: 'math', triggerKind: 'tab', priority: 50, wordBoundary: true },
    tabStops: 1,
    description: 'Underline',
    category: 'Decorations',
  },
  {
    trigger: 'conj',
    replacement: '\\overline{$1}',
    options: { mode: 'math', triggerKind: 'tab', priority: 50, wordBoundary: true },
    tabStops: 1,
    description: 'Conjugate (overline)',
    category: 'Decorations',
  },
];
