import { Snippet } from './index';

export const environmentSnippets: Snippet[] = [
  {
    trigger: 'beg',
    replacement: '\\begin{$1}\n$2\n\\end{$1}',
    options: { mode: 'both', triggerKind: 'tab', priority: 70, wordBoundary: true },
    tabStops: 2,
    description: 'Generic \\begin{} \\end{} environment',
    category: 'Environments',
  },
  {
    trigger: 'ali',
    replacement: '\\begin{aligned}\n$1\n\\end{aligned}',
    options: { mode: 'math', triggerKind: 'tab', priority: 65, wordBoundary: true },
    tabStops: 1,
    description: 'Aligned environment',
    category: 'Environments',
  },
  {
    trigger: 'case',
    replacement: '\\begin{cases}\n$1\n\\end{cases}',
    options: { mode: 'math', triggerKind: 'tab', priority: 65, wordBoundary: true },
    tabStops: 1,
    description: 'Cases environment',
    category: 'Environments',
  },
  {
    trigger: 'pmat',
    replacement: '\\begin{pmatrix}\n$1\n\\end{pmatrix}',
    options: { mode: 'math', triggerKind: 'tab', priority: 65, wordBoundary: true },
    tabStops: 1,
    description: 'Parenthesized matrix',
    category: 'Environments',
  },
  {
    trigger: 'bmat',
    replacement: '\\begin{bmatrix}\n$1\n\\end{bmatrix}',
    options: { mode: 'math', triggerKind: 'tab', priority: 65, wordBoundary: true },
    tabStops: 1,
    description: 'Bracketed matrix',
    category: 'Environments',
  },
  {
    trigger: 'vmat',
    replacement: '\\begin{vmatrix}\n$1\n\\end{vmatrix}',
    options: { mode: 'math', triggerKind: 'tab', priority: 65, wordBoundary: true },
    tabStops: 1,
    description: 'Determinant matrix',
    category: 'Environments',
  },
  {
    trigger: 'mat',
    replacement: '\\begin{matrix}\n$1\n\\end{matrix}',
    options: { mode: 'math', triggerKind: 'tab', priority: 60, wordBoundary: true },
    tabStops: 1,
    description: 'Plain matrix',
    category: 'Environments',
  },
  {
    trigger: 'arr',
    replacement: '\\begin{array}{$1}\n$2\n\\end{array}',
    options: { mode: 'math', triggerKind: 'tab', priority: 65, wordBoundary: true },
    tabStops: 2,
    description: 'Array environment',
    category: 'Environments',
  },

  // Theorem-like environments (for text mode / document level)
  {
    trigger: 'thm',
    replacement: '\\begin{theorem}\n$1\n\\end{theorem}',
    options: { mode: 'text', triggerKind: 'tab', priority: 65, wordBoundary: true },
    tabStops: 1,
    description: 'Theorem environment',
    category: 'Environments',
  },
  {
    trigger: 'lem',
    replacement: '\\begin{lemma}\n$1\n\\end{lemma}',
    options: { mode: 'text', triggerKind: 'tab', priority: 65, wordBoundary: true },
    tabStops: 1,
    description: 'Lemma environment',
    category: 'Environments',
  },
  {
    trigger: 'prf',
    replacement: '\\begin{proof}\n$1\n\\end{proof}',
    options: { mode: 'text', triggerKind: 'tab', priority: 65, wordBoundary: true },
    tabStops: 1,
    description: 'Proof environment',
    category: 'Environments',
  },
  {
    trigger: 'def',
    replacement: '\\begin{definition}\n$1\n\\end{definition}',
    options: { mode: 'text', triggerKind: 'tab', priority: 65, wordBoundary: true },
    tabStops: 1,
    description: 'Definition environment',
    category: 'Environments',
  },
  {
    trigger: 'cor',
    replacement: '\\begin{corollary}\n$1\n\\end{corollary}',
    options: { mode: 'text', triggerKind: 'tab', priority: 65, wordBoundary: true },
    tabStops: 1,
    description: 'Corollary environment',
    category: 'Environments',
  },
  {
    trigger: 'prop',
    replacement: '\\begin{proposition}\n$1\n\\end{proposition}',
    options: { mode: 'text', triggerKind: 'tab', priority: 60, wordBoundary: true },
    tabStops: 1,
    description: 'Proposition environment',
    category: 'Environments',
  },
  {
    trigger: 'rmk',
    replacement: '\\begin{remark}\n$1\n\\end{remark}',
    options: { mode: 'text', triggerKind: 'tab', priority: 65, wordBoundary: true },
    tabStops: 1,
    description: 'Remark environment',
    category: 'Environments',
  },
  {
    trigger: 'ex',
    replacement: '\\begin{example}\n$1\n\\end{example}',
    options: { mode: 'text', triggerKind: 'tab', priority: 65, wordBoundary: true },
    tabStops: 1,
    description: 'Example environment',
    category: 'Environments',
  },
];
