import { Snippet } from './index';

export const operatorSnippets: Snippet[] = [
  // Calculus operators
  {
    trigger: 'lim',
    replacement: '\\lim_{$1 \\to $2}',
    options: { mode: 'math', triggerKind: 'tab', priority: 60, wordBoundary: true },
    tabStops: 2,
    description: 'Limit',
    category: 'Calculus',
  },
  {
    trigger: 'sum',
    replacement: '\\sum_{$1}^{$2}',
    options: { mode: 'math', triggerKind: 'tab', priority: 60, wordBoundary: true },
    tabStops: 2,
    description: 'Summation',
    category: 'Calculus',
  },
  {
    trigger: 'prod',
    replacement: '\\prod_{$1}^{$2}',
    options: { mode: 'math', triggerKind: 'tab', priority: 60, wordBoundary: true },
    tabStops: 2,
    description: 'Product',
    category: 'Calculus',
  },
  {
    trigger: 'int',
    replacement: '\\int_{$1}^{$2} $3 \\, d$4',
    options: { mode: 'math', triggerKind: 'tab', priority: 60, wordBoundary: true },
    tabStops: 4,
    description: 'Integral',
    category: 'Calculus',
  },
  {
    trigger: 'oint',
    replacement: '\\oint_{$1}',
    options: { mode: 'math', triggerKind: 'tab', priority: 60, wordBoundary: true },
    tabStops: 1,
    description: 'Contour integral',
    category: 'Calculus',
  },
  {
    trigger: 'dint',
    replacement: '\\int_{-\\infty}^{\\infty}',
    options: { mode: 'math', triggerKind: 'tab', priority: 55, wordBoundary: true },
    description: 'Integral from -inf to inf',
    category: 'Calculus',
  },
  {
    trigger: 'part',
    replacement: '\\frac{\\partial $1}{\\partial $2}',
    options: { mode: 'math', triggerKind: 'tab', priority: 60, wordBoundary: true },
    tabStops: 2,
    description: 'Partial derivative',
    category: 'Calculus',
  },
  {
    trigger: 'nabla',
    replacement: '\\nabla',
    options: { mode: 'math', triggerKind: 'auto', priority: 50, wordBoundary: true },
    description: 'Nabla',
    category: 'Calculus',
  },
  {
    trigger: 'grad',
    replacement: '\\nabla',
    options: { mode: 'math', triggerKind: 'tab', priority: 50, wordBoundary: true },
    description: 'Gradient (nabla)',
    category: 'Calculus',
  },
  {
    trigger: 'div',
    replacement: '\\nabla \\cdot',
    options: { mode: 'math', triggerKind: 'tab', priority: 50, wordBoundary: true },
    description: 'Divergence',
    category: 'Calculus',
  },
  {
    trigger: 'curl',
    replacement: '\\nabla \\times',
    options: { mode: 'math', triggerKind: 'tab', priority: 50, wordBoundary: true },
    description: 'Curl',
    category: 'Calculus',
  },

  // Comparison & relation operators
  {
    trigger: 'equiv',
    replacement: '\\equiv',
    options: { mode: 'math', triggerKind: 'tab', priority: 50, wordBoundary: true },
    description: 'Equivalent',
    category: 'Operators',
  },
  {
    trigger: 'approx',
    replacement: '\\approx',
    options: { mode: 'math', triggerKind: 'tab', priority: 50, wordBoundary: true },
    description: 'Approximately',
    category: 'Operators',
  },
  {
    trigger: 'prop',
    replacement: '\\propto',
    options: { mode: 'math', triggerKind: 'tab', priority: 50, wordBoundary: true },
    description: 'Proportional to',
    category: 'Operators',
  },
  {
    trigger: 'perp',
    replacement: '\\perp',
    options: { mode: 'math', triggerKind: 'tab', priority: 50, wordBoundary: true },
    description: 'Perpendicular',
    category: 'Operators',
  },

  // Named operators
  {
    trigger: 'det',
    replacement: '\\det',
    options: { mode: 'math', triggerKind: 'tab', priority: 50, wordBoundary: true },
    description: 'Determinant',
    category: 'Operators',
  },
  {
    trigger: 'dim',
    replacement: '\\dim',
    options: { mode: 'math', triggerKind: 'tab', priority: 50, wordBoundary: true },
    description: 'Dimension',
    category: 'Operators',
  },
  {
    trigger: 'ker',
    replacement: '\\ker',
    options: { mode: 'math', triggerKind: 'tab', priority: 50, wordBoundary: true },
    description: 'Kernel',
    category: 'Operators',
  },
  {
    trigger: 'img',
    replacement: '\\operatorname{Im}',
    options: { mode: 'math', triggerKind: 'tab', priority: 50, wordBoundary: true },
    description: 'Image',
    category: 'Operators',
  },
  {
    trigger: 'hom',
    replacement: '\\operatorname{Hom}',
    options: { mode: 'math', triggerKind: 'tab', priority: 50, wordBoundary: true },
    description: 'Hom',
    category: 'Operators',
  },
  {
    trigger: 'sup',
    replacement: '\\sup',
    options: { mode: 'math', triggerKind: 'tab', priority: 50, wordBoundary: true },
    description: 'Supremum',
    category: 'Operators',
  },
  {
    trigger: 'inf',
    replacement: '\\inf',
    options: { mode: 'math', triggerKind: 'tab', priority: 50, wordBoundary: true },
    description: 'Infimum',
    category: 'Operators',
  },
  {
    trigger: 'max',
    replacement: '\\max',
    options: { mode: 'math', triggerKind: 'tab', priority: 50, wordBoundary: true },
    description: 'Maximum',
    category: 'Operators',
  },
  {
    trigger: 'min',
    replacement: '\\min',
    options: { mode: 'math', triggerKind: 'tab', priority: 50, wordBoundary: true },
    description: 'Minimum',
    category: 'Operators',
  },

  // Binary operations
  {
    trigger: 'otimes',
    replacement: '\\otimes',
    options: { mode: 'math', triggerKind: 'tab', priority: 50, wordBoundary: true },
    description: 'Tensor product',
    category: 'Operators',
  },
  {
    trigger: 'oplus',
    replacement: '\\oplus',
    options: { mode: 'math', triggerKind: 'tab', priority: 50, wordBoundary: true },
    description: 'Direct sum',
    category: 'Operators',
  },
  {
    trigger: 'wedge',
    replacement: '\\wedge',
    options: { mode: 'math', triggerKind: 'tab', priority: 50, wordBoundary: true },
    description: 'Wedge product',
    category: 'Operators',
  },
  {
    trigger: 'vee',
    replacement: '\\vee',
    options: { mode: 'math', triggerKind: 'tab', priority: 50, wordBoundary: true },
    description: 'Vee',
    category: 'Operators',
  },

  // Infinity and special constants
  {
    trigger: 'ooo',
    replacement: '\\infty',
    options: { mode: 'math', triggerKind: 'auto', priority: 60, wordBoundary: false },
    description: 'Infinity',
    category: 'Symbols',
  },
  {
    trigger: 'OO',
    replacement: '\\infty',
    options: { mode: 'math', triggerKind: 'auto', priority: 60, wordBoundary: false },
    description: 'Infinity',
    category: 'Symbols',
  },
  {
    trigger: 'lll',
    replacement: '\\ell',
    options: { mode: 'math', triggerKind: 'auto', priority: 60, wordBoundary: false },
    description: 'Ell',
    category: 'Symbols',
  },
  {
    trigger: 'dag',
    replacement: '\\dagger',
    options: { mode: 'math', triggerKind: 'tab', priority: 50, wordBoundary: true },
    description: 'Dagger',
    category: 'Symbols',
  },
];
